version: "3.9"

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "1001:2001"

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "1002:2002"
